module.exports.BEM_VINDO = "BEM_VINDO";
module.exports.ESCOLHA_ATENDIMENTO = "ESCOLHA_ATENDIMENTO";
module.exports.ATENDIMENTO_EXTRACAO_DATA = "ATENDIMENTO_EXTRACAO_DATA";
module.exports.ATENDIMENTO_EXTRACAO_HORA = "ATENDIMENTO_EXTRACAO_HORA";
module.exports.ATENDIMENTO_FUNCIONARIO = "ATENDIMENTO_FUNCIONARIO";
module.exports.CONFIRMACAO_NOVO_ATENDIMENTO = "CONFIRMACAO_NOVO_ATENDIMENTO";